- name: Apt Update repositories cache
  apt:
    update_cache: yes

- name: Install docker.io
  package: name=docker.io state=present

- name: Install docker compose
  package: name=docker-compose state=present

- name: Start docker service
  service: name=docker state=started

- name: Add user to docker group
  user: name=ubuntu group=docker state=present